//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.06 at 05:06:00 PM CET 
//


package it.polito.dp2.RNS.rest.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.RNS.rest.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.RNS.rest.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Paths }
     * 
     */
    public Paths createPaths() {
        return new Paths();
    }

    /**
     * Create an instance of {@link Paths.Path }
     * 
     */
    public Paths.Path createPathsPath() {
        return new Paths.Path();
    }

    /**
     * Create an instance of {@link NodeResult }
     * 
     */
    public NodeResult createNodeResult() {
        return new NodeResult();
    }

    /**
     * Create an instance of {@link RelationshipResult }
     * 
     */
    public RelationshipResult createRelationshipResult() {
        return new RelationshipResult();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Paths.Path.Nodes }
     * 
     */
    public Paths.Path.Nodes createPathsPathNodes() {
        return new Paths.Path.Nodes();
    }

    /**
     * Create an instance of {@link Paths.Path.Relationships }
     * 
     */
    public Paths.Path.Relationships createPathsPathRelationships() {
        return new Paths.Path.Relationships();
    }

    /**
     * Create an instance of {@link NodeResult.Data }
     * 
     */
    public NodeResult.Data createNodeResultData() {
        return new NodeResult.Data();
    }

}
